### ISSUE TITLE
BUG-138 Text Converter: attacks are not properly parsed

### ISSUE THREAD

**Issue by JulGvoz** [Pf2eToolsOrg/Pf2eTools#110]
Steps to reproduce
1. Input the text for the **Sample Creature** (seen in Help tab, which can be opened with the button in the bottom left)
2. Click **Parse**
3. Observe that the line corresponding to the creature's attack:
```
Melee [one-action] hand +24 (finesse, magical), Damage 4d8 negative plus paralyzing touch
```
is converted into
```json
"attacks": [
	{
		"range": "Melee",
		"activity": {
			"number": 1,
			"unit": "action"
		},
		"traits": [
			"finesse",
			"magical"
		],
		"name": "hand",
		"bonus": 24,
		"damage": "{@damage 4d8} negative plus paralyzing touch"
	}
]
```
Notably, it has `"bonus": 24` instead of `"attack": 24`, and it is missing types:
```json
"types": [
	"negative"
]
```
When viewing the added creature in Bestiary, it shows up like this:
![image](https://user-images.githubusercontent.com/46909274/181713968-96c174ab-0021-4d8a-9960-d0c631e6ec55.png)
Instead of this:
![image](https://user-images.githubusercontent.com/46909274/181714018-ac42b11d-a4ba-4a57-a313-f4a786faad54.png)

Severity
Low

**Comment by MrVauxs** [comment]
Fixed in [v0.6.3](https://github.com/Pf2eToolsOrg/Pf2eTools/releases/tag/v0.6.3).
