### ISSUE TITLE
BUG-156 Archetype page loads with error toast

### ISSUE THREAD

**Issue by crawltracker** [Pf2eToolsOrg/Pf2eTools#130]
Steps to reproduce
Load archetypes page

Severity
Low

Additional information
https://i.ibb.co/s3t0kp1/Screenshot-2022-10-02-at-20-19-56.png
Also noticed that it redirects from `/archetypes.html` to just `/archetypes` :thinking:

- spap#9812
Verification: 0

**Comment by naxhh** [comment]
Can't reproduce on latest versions of chrome & firefox.

**Comment by lorddusk** [comment]
@naxhh please don't use the github tickets for commenting, everything is done through the Discord server. Any and all comments here will be ignored by the bot, and possibly won't be seen by the authors.

**Comment by crawltracker** [comment]
Note - vauxs#0

Resolved - Stale
