### ISSUE TITLE
Gatewalkers

### ISSUE THREAD

**Issue by MrVauxs** [Pf2eToolsOrg/Pf2eTools#139]
- [x] [Player's Guide](https://paizo.com/community/blog/v5748dyo6si7s?Introducing-the-Gatewalkers-Player-s-Guide) 
- [x] The Seventh Arch
- [x] They Watched the Stars
- [x] Dreamers of the Nameless Spires

**Comment by Spappz** [comment]
PG, 1, and 3 by Vauxs
