### ISSUE TITLE
Books button on index page leads to a 404

### ISSUE THREAD

**Issue by fotoply** [Pf2eToolsOrg/Pf2eTools#326]
Steps to reproduce

1. Go to https://pf2etools.com/
2. Click the big "Books" button
3. 404 page not found (https://pf2etools.com/books.html)

Severity
Low

Additional Information
Image of the 404
![image](https://github.com/Pf2eToolsOrg/Pf2eTools/assets/446006/f0a9259f-e158-40f1-b1e5-1ddf1ccddbde)

**Comment by Spappz** [comment]
Fixed for next release
