### ISSUE TITLE
GM Screen is broken without search/index.json

### ISSUE THREAD

**Issue by 7m0E7TRWiyc7eJlETAgDR-rp6HLJf2yvSnJLuQL** [Pf2eToolsOrg/Pf2eTools#343]
After cloning the repository and running a server on it, I noticed that it was failing with an error of 'search/index.json' 404.  After copying the index.json from pf2etools.com and creating a 'search' folder to place it in, the gm screen works.
[index.json](https://github.com/Pf2eToolsOrg/Pf2eTools/files/13493485/index.json)

**Comment by Spappz** [comment]
Did you `npm run build` before `npm run serve:dev`? You might very well need to rebuild the index yourself using the former command.

**Comment by Spappz** [comment]
Closing as stale.
