### ISSUE TITLE
FEAT-Bestiary images from Archives of Nethys

### ISSUE THREAD

**Issue by Kuiriel** [Pf2eToolsOrg/Pf2eTools#362]
Information
Is there any way to preload the bestiary images rather than only having them available as a link? Preloading images doesn't seem to do it.

Who would use it?
Everyone who will be using the tool offline.

How would it work?
Source images from publicly available locations like archives of Nethys.

Why should this be added?
Helps with immersion when I can describe the beast better or show the picture.

**Comment by MrVauxs** [comment]
Archives of Nethys images are not available to the public. You may look at it as part of their website, and thus the links, but we cannot download them or share them as we do not have a licensing agreement with Paizo.

**Comment by Kuiriel** [comment]
Thank you.
